
import Head from "next/head";
import { Inter } from "next/font/google";
import PanelControl from "@/components/PanelControl"
import Formulario from "@/components/Formulario";
import Presentacion from "@/components/Presentacion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Flyer GEBA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='fondo' />
      <div className='d-flex flex-column vw-100 vh-100 px-3 pt-3'>
          <nav className="row g-1">
            <PanelControl />
          </nav>
          <header className="col">
            <form>
              <Formulario />
            </form>
          </header>
          <main className="col">
            <Presentacion />
          </main> 
      </div>
    </>
  );
}
